Repository PyTorchKorea/tutorials-kr, pull requests merged in 2020-11, with the labels that each got.

#109 intermediate_source/spatial_transformer_tutorial.py 번역 (#99)
  intermediate_source/spatial_transformer_tutorial.py
Labels: 컨트리뷰톤, 피드백 요청

#165 translate beginner_source-nlp-advanced_tutorial
  beginner_source/nlp/advanced_tutorial.py
Labels: 컨트리뷰톤

#112 recipes/profiler.py 번역 (#100)
  recipes_source/recipes/profiler.py
  recipes_source/recipes_index.rst
Labels: 컨트리뷰톤, 피드백 요청

#138 intermediate_source/memory_format_tutorial.py 번역 (#129)
  intermediate_source/memory_format_tutorial.py
Labels: 컨트리뷰톤, 피드백 요청

#139 Beginner source/dcgan faces tutorial.py 번역
  beginner_source/dcgan_faces_tutorial.py
Labels: 추가작업필요, 컨트리뷰톤, 피드백 요청
